### ISSUE TITLE
config_flow missing?

### ISSUE THREAD

**Issue by stefanke** [vas3k/home-assistant-berlin-transport#10]
I can not install the sensor component following the documentation. 

I tried the example configuration-yaml as well as a custom one with my own stops and ids. But whenever I want to add the entity "Berlin (BVG) and Brandenburg (VBB) transport" I get the following error in the home assistance interface: "Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}"

In the log file it shows "2023-02-09 09:41:57.597 ERROR (MainThread) [homeassistant. config_entries] Error occurred loading configuration flow for integration berlin_transport: No module named 'custom_ components berlin_transport.config_flow'"

I can not find the file berlin_transport.config_flow in the git - but I'm new to home assistant and do not understand (yet) the whole concept of flows.

![Screenshot 2023-02-09 at 10 07 48](https://user-images.githubusercontent.com/15725888/217766942-383cd160-b93d-48e2-a246-e1f4a4f74d2f.jpg)

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by vas3k** [comment]
> I can not find the file berlin_transport.config_flow in the git - but I'm new to home assistant and do not understand (yet) the whole concept of flows.

You're right, the concept of "configuration flows" is new in Home Assistant and my sensor just does not support it yet :)

So you don't need to use them.

Configuration flows is a replacement for manually adding a sensor to `configuration.yml`. So if you have already added it to the file manually, you need to restart Home Assistant and wait until the sensor appears in the entities tab or on the main dashboard.

After re-starting check logs again, there should be something about it. Or just wait.

**Comment by stefanke** [comment]
Thanks vas3k! 
After a couple of restarts it did not appear yet - but also did not threw any errors as long as I do not try to add it manually.  
I was just confused because in the manifest.json I found the entry config_flow: true. 

Guess I just have to wait a bit longer. Thanks!

**Comment by stefanke** [comment]
ok, I searched in the wrong place - I was looking under "integrations" for an entry but found everything under "entities" now. Sorry for the confusion. Problem solved...
