### ISSUE TITLE
Update API to V6

### ISSUE THREAD

**Issue by Gamdschi** [vas3k/home-assistant-berlin-transport#15]
The V5 of the vbb transport rest API is marked as deprecated and currently not responding.

**Comment by prepor** [comment]
I have my own port of this for Elixir, it was broken today, so I went here to check if someone else has similar problems. As I see, I'm not alone :) How I fixed it: 

- they changed IDs of some stops, so you probably have to reconfigure them
- for API endpoint `https://v6.vbb.transport.rest/stops/#{id}/departures` they now wrap the list of departures with a map with key `departures`.

For me, these changes fixed a problem.

**Comment by Gamdschi** [comment]
Thank you that did indeed fix the problem
