### ISSUE TITLE
Add logo on integration

### ISSUE THREAD

**Issue by mrueg** [vas3k/home-assistant-berlin-transport#29]
According to https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/ a logo could be added here to make it easy to find: https://github.com/home-assistant/brands

Maybe this can be used? https://de.wikipedia.org/wiki/Datei:VBB-Logo.svg

**Comment by vas3k** [comment]
Let's use the VBB logo. There is already integration with the BVG logo, so we will be different :)

**Comment by mrueg** [comment]
https://github.com/home-assistant/brands/pull/5077
